FROM openjdk:8
EXPOSE 8080
ADD build/libs/FisrtSpringBoot_With_Gradle-0.0.1-SNAPSHOT.war FisrtSpringBoot_With_Gradle-0.0.1-SNAPSHOT.war
ENTRYPOINT ["java","-jar","/FisrtSpringBoot_With_Gradle-0.0.1-SNAPSHOT.war"]